### ISSUE TITLE
Is Registred Property 

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#10]
This is a little different that I anticipated. We need to have to computed properties on the backend. First is, isRegistredSire and the second isRegisteredDamSIre. Both of those should be searchable on the backend. 

So, I am thinking we should be able to send up in the request with those toggled and true or false. 

To compete the task should pass the following tests
- [x] When searching we should be able to ask for listings that have a **sire** that is registered(We won't ever search for isNotRegistered) 
- [x] When searching we should be able to ask for listings that have a **dam** sire that is registered(We won't ever search for isNotRegistered)
- [x] The horse model should have a property that tells us if the horse has a registered **sire** 
- [x] The horse model should have a property that tells us if the horse has a registered **dam sire** 
- [x] When checking if a sire or dam sire is registered it should be something you calculate, not something we send you. To calculate this we should cross check our sire lists with dam and dam sire that a listings has.

**Comment by clerenge** [comment]
isRegisteredRefactor branch is pushed and has been published to dev environment. If all is good, I will merge it with official dev branch. Tested through postman and worked well.
