### ISSUE TITLE
Most Recent Filter 

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#11]
I am not sure what happened or if I don't have the correct number to send you but relevance is not sorted by most recently listed.

To complete this task we need to add to our existing orderby list to add **date.** as an option. This should be the default filter if we don't send you something and order listings by most recently listed.

**Comment by clerenge** [comment]
Changed default search to Order By OriginalDateListed DESC(descending)

**Comment by clerenge** [comment]
Tested in postman is working. Send OrderBy as true and orderByType as 10. If OrderBy is sent in as false(default ordering) it will order by OriginalDateListed descending
