### ISSUE TITLE
Horse Description Size

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#12]
We need to set the string size of a horse's description to be a larger size. In theory we should be able to fit about 5 paragraphs in the description. 

[Link to fake text](https://loremipsum.io/generator/?n=5&t=p)

**Comment by clerenge** [comment]
I changed the datatype of description in the database from nvarchar(500) to nvarchar(max) which will allow for what we need. This required dropping and re-creating the active listings table. All the data was retained though. This is live on DEV
