### ISSUE TITLE
Remove Field Requirements When Updating a Listing

### ISSUE THREAD

**Issue by dacarver** [Betzer09/HorseApp2#13]
When updating a listing we require certain fields. If we don't send these values up, they will be overriden with default values. The requirement for including these fields should be removed.

The fields required are
`horseAge`
`listingID`
`photoData`
`callForPrice`

**Comment by clerenge** [comment]
Unfortunately, ActiveListingId has to be required because it is how we specify which listing we are updating. For photoData, I am sending updates without photos and it seems to work, if there's an issue I am not seeing let me know. CallForPrice and HorseAge I am able to fix for you though!
