### ISSUE TITLE
Remove ranchPhoto Field on Horse Listing

### ISSUE THREAD

**Issue by dacarver** [Betzer09/HorseApp2#19]
The ranchPhoto field has been moved to the seller model, but we are still required to include a value for this in the horse object when submitting a new listing. Please remove this requirement on the horse object (but keep it as is in the seller object).

**Comment by clerenge** [comment]
You don't have to send in RanchPhoto as a parameter in InsertActiveListing. Pull request is not needed

**Comment by clerenge** [comment]
Change was done in database
