### ISSUE TITLE
Update Sire Lists

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#3]
You will need to update the lists sires lists. What needs changed is to the right in parenthises

**Reining List**
Late Nite Stopper (Night)
Peptoboonsmal (Add to list)
One Time Pepto (Add to list)
CD Olena (Add to list)
Playgun (Add to list)

**Cow Horse**
Cowtwons Cat (Cowtowns)
Dont Stopp Beliefen (Believin)
He’s Playingforkeeps (Hes)
He’s Wright On (Hes)
Madaley Rey (Mandalay)
Matt Dillon Dun t (It)
CD Olena (Add to list)
Reyszin The Cash (Reyzin)
Shine Outlaw (Shiney)
Step-in On Sparks (Steppin)
Whiskey N Diamonds (Whizkey)

**Cutting**
Cd Lights (CD)
Cr Gotcha Covered (CR)
Cr Highlight (CR)
Ebr Kitty Hawk (EBR)
High Brow Cd (CD)
Metalic AI (Metallic)
Nrr Cat King Cole (NRR)
Pepto Bro Cd (CD)
Pg Heavily Armed (PG)
CD Olena (Add to list)
Tr Dual Rey (TR)
Wr This Cats Smart (WR)

**Barrel**
This Guy A Keeper (Guyz)

**Comment by clerenge** [comment]
Done
