### ISSUE TITLE
Add Roping as a Sire Type

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#4]
We need to add the **Roping type to the backend** Searching & Creating should still be functional.

**ROPING Sire List**
A Shiner Named Sioux
A Sparkling Vintage
A Vintage Smoke
All American Vintage
AlwaysShineYerGunsUp
ARC Gunna Sparkya
ARC Gunnabeabigstar
Arlosa Whiz
Armani Cat
Auspicious Cat
Bamacat
Banjo Whiz
Be Aech Enterprise
Bet Hesa Cat
BFR Igniting Spark
Big Chex To Cash
Blind Sided
Blue One Time
Boom Shernic
Boomboomvoodoodaddy
Boomernic
Boon N Crockett
Boon San
Boon Too Suen
Brother Jackson
Brother Tuff Wood
Call Me Mitch
Cant Kick This Cat
Captain Barbossa
Cat A Rey
Cat Man Do
Cats Merada
Cats Picasso
Cattalou
Catty Hawk
CD Diamond
CD Highlights
CD Lights
CD Olena
Charmin Jose
Chexmaster
Chic Dreamin
Chics Loaded Gun
Chocolate Chic Olena
Colonels Lil Gun
Colonels Shining Gun
Colonels Smart Spook
Colonels Smoking Gun
Conquistador Whiz
Cool N Hot
Copy Cat
Country Bay Berry
Cowboy Smarts
Cowtowns Cat
CR Gotcha Covered
CR Highlight
Cromed Out Mercedes
Custom Cash Advance
Custom Crome
Custom Legend
Custom Made Gun
Custom Pistol
Customs Pistol Pete
Daddy Day Care
Dandy Cat
Desires Little Rex
Docs Hickory
Dont Stopp Believin
Dual Pep
Dual R Smokin
Dual Rey
Dual Reyish
Dual Smart Rey
Dualin Boon
Dualin Stargun
Dun It For Whizkey
Dun It Gotta Gun
Dun It Regally
Einstein
Einsteins Revolution
Electric Code
Electric Snow
Epic Titan
Fantastic Cat
Fiestas Gotta Gun
Finest China Rose
FM Cottonwood
Footwork Revolution
Freckles Got Ashiner
Friday Night Shiner
Funny B Blue Muchaman
Gallo Del Cielo
Gallo Pocos Cross
Grays Starlight
Got Guns A Blazin
Gotta Nifty Gun
Gotta Twist It Up
Gunna Stop
Gunnatrashya
Gunner Boy
Gunner Dun It Again
Gunner On Ice
Gunners Enterprise
Gunners Indian
Gunners Last Dance
Gunners Special Nite
Gunners Tinseltown
Gunners Trashman
Gunnin For Chicks
Gunnit
Guns R For Shootin
Guthrie City Limits
Guys Canyon Moon
Hang Ten Surprize
Hashtags
Heavenly Firewater
Heavy Duty Chex
Hes Playingforkeeps
Hes Wright On
Heza Shiney Kodo
HF Mobster
Hickory Chic Olena
Hickory Holly Time
High Brow Cat
High Brow CD
High Brow Jackson
High Brow Shiner
High Roller Whiz
Hollywood Cool Gun
Hollywood Dun It
Hollywood Jac 86
Hollywood Reminic
Hollywoodstinseltown
Hottish
Hydrive Cat
Im Countin Checks
Im The Chic Magnet
In Like Flinn
Inferno Sixty Six
Inwhizable
Its All About Smart
Jacs Electric Spark
Jasons Peptolena
Jerry Lees Surprise
Jesses Topaz
Ju Juzz Gunslinger
Judge Boon
Kinenos Moon
Kit Kat Sugar
Late Night Stopper
Legendary Jac
Lena Spark
Leta Lena Whiz
Like A Diamond
Lil Catbaloo
Lil Dreamin Magnum
Lil Joe Cash
Lil Ruf Peppy
Louis The Cat
Magicality
Magnum Chic Dream
Magnum With A Dream
Major Bonanza
Malt Whizkey
Mamas Duel N At Boon
Mandalay Rey
Marsala Red
Marthas Mega Jac
Matt Dillon Dun It
Mega Watt Shine
Memorable Revolution
Metallic AI
Metallic Cat
Metallic Masterpiece
Metallic Rebel
Meteles Cat
Mister Montana Nic
Mister Nicadual
Mister Smarts
Modern Gun
Mr Electric Spark
Mr Peppys Freckles
Mr Playinstylish
Must Have Guns
My Royal Gun
Mylanta Lena
Natural Bottom
Nic It In The Bud
Nicnac Enterprise Jr
Nice Black Diamond
Nice Little Bud
No Guns Please
No Pressure On Me
Not Ruf At All
NRR Cat King Cole
Nu Chex To Cash
Olena Oak
Once A Von A Time
Once In A Blu Boon
One Fine Vintage
One Roan Peptos
One Time Pepto
One Time Royalty
Outta Dough
Pale Face Dunnit
Payaso Rojo Gunner
Peptoboonsmal
Peptos Boon Shadow
Peptos Stylish Oak
PG Heavily Armed
Phame
Platinum Vintage
Playgun
Playin Attraction
Playin Stylish
Pretty Peppy Chec
PS Mega Shine Chic
Purdy Boy Flash
Quenaisalena
Red Hot Metal
REF Black Mamba
REF Camafeo
Reminic
Reydioactive
Reys Dual Badger
Reyzin The Cash
Rockin W
Rocky Mountain Blues
Rooster Sparks
Roosters Wrangler
Rowdy Yankee
Royal And Famous
Royal Fletch
Ruf Lil Magnum
Ruf Hearted Jac
Rufanicki
Ruff Spook
Sannman
SDP Blue Blood
SG Frozen Enterprize
Shady Lil Starlight
Shine Big Time
Shine Chic Shine
Shine N Spook
Shine On Line
Shiners Nickle
Shiners Voodoo Dr
Shiney Outlaw
Shining Cat
Shining Spark
Show Me The Buckles
SHR QTs Diamondcutter
Sigala Rey
Sir Long Legs
Sixes Country
Sixes Pick
Sixes Sixgun
SJR Diamond Mist
SM Steping Junior
Smart And Shiney
Smart Aristocrat
Smart Boons
Smart Chic Olena
Smart Like Juice
Smart Lil Roos
Smart Little Lena
Smart Luck
Smart Santana
Smart Shiners Spook
Smart Spook
Smart Starbuck
Smart Time Pepto 10
Smoking Whiz
Smooth As A Cat
Smooth Talkin Style
Smooths First Tobicat
Snap Dun The Bases
Snip O Lution
Snipers Smoking Gun
Solano Cat
Sophisticated Catt
Sparkling Major
Sparks Of Glory
Spat Olena
Special Made Whiskey
Spooks Gotta Gun
Spooks Gotta Run
Spooks Gotta Whiz
Spots Hot
Star Spangled Whiz
Starlight Cat
Starlights Wrangler
Step It Up Jak
Steppin On Sparks
Stevie Rey Von
Strum Me A Banjo
Sugar Little Step
Sweet Lil Pepto
The Animal
The Boon
The Chex Factor
The Crow Bar
The Kids Gotta Gun
The Rey Gun
The Sweet Spot
Third Cutting
Time For The Diamond
Tinker With Guns
Tinsel Jac
Tinseltown Flash
Tinseltown Fly Guy
Tomcat Chex
Topsail Cody
Topsail Whiz
Trashadeous
TR Dual Rey
TR Illuminator Cash
TR Smokin Dually
Travelin Jonez
Tricked Out Spook
Very Especial Cat
Wagon Stake
Walla Walla Starbuck
Walla Walla Whiz
Wallawalla Bangbang
West Coast Whiz
Whitey N Hollywood
Whiz N Tag Chex
Whiz Van Winkle
Whizard Jac
Whizkey N Diamonds
Whizkey On The Rocks
Whizs Chic A Dee
Whodini
Whos The Whiz Kid
Wimps Cool Breeze
Wimpy Chic
Wimpyneedsacocktail
Wimpys High Bid
Wimpys Little Step
Wimpys Littlecolonel
Wimpys Tinseltown
Woody Be Tuff
WR This Cats Smart
Wranglered
Wranglin In Chex
Yellow Jersey
Zack T Wood

**Comment by clerenge** [comment]
Done
