### ISSUE TITLE
Defaulting listing Order

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#6]
Initial sort by on results done by "most recent listed" rather than "relevance" which is alphabetical 

To complete this task to do the follwing
- [ ] Add to OrderBy a sort by date(Most recent)
- [ ]  Make sure that relevance is sorting by horse name in alphabetical order
- [ ]  Test on the dev server with Austin before deploying.

**Comment by clerenge** [comment]
So for all sorts we want to order by date first?
