### ISSUE TITLE
Call For Price 

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#7]
**Don't start this task**

We need to add a property called 'shouldCallForPrice' If this is true a horse listing isn't required to have a price. 

To complete this task do the follwing
- [x] Add a 'ShouldCallForPrice property'
- [x] By default all previously existing listings should have this set to false
- [x] When sorting low to hight a horse with 'ShouldCallForPrice' as true should show up at the bottom
- [x] When sorting high to low a horse with 'ShouldCallForPrice' as true should show up at the top
- [x] Test locally on dev server

**Comment by clerenge** [comment]
Done
