### ISSUE TITLE
Search By Height Filter

### ISSUE THREAD

**Issue by Betzer09** [Betzer09/HorseApp2#8]
We need to be able to search by a horses height(Aka hands). Existing listing will not have this, but the new ones will. If the user searching for a height and the horse doesn't have a height it should not be returned. 

- [x] Backwards compatible(old listings should get a height of 0)
- [x] Add search by height to the current filter method, test all other filters to make sure nothing breaks
- [x] Add a property to the horse so we can create a horse with the height property.

**Comment by clerenge** [comment]
Done
